openapi: 3.1.0
info:
  version: 0.1.0
  title: Voucher Launcher
  #termsOfService: https://example.com/terms/
  contact:
    name: Developer Support
    email: developer@botio.io
  #  url: http://example.com/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  #x-logo:
  #  url: https://redocly.github.io/openapi-template/logo.png
  description: >
    # Introduction

    Voucher Launcher provides a voucher management and delivery service.
tags:
  - name: Voucher
    description: Voucher operations
servers:
  - url: https://api.botio.io/voucher/v1
paths:
  /vouchers:
    $ref: paths/vouchers.yaml
components:
  securitySchemes:
    API_Key:
      type: apiKey
      in: header
      name: X-API-Key
